on:
  github:
    branches:
      only: master
jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
     xray:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
      ref: context.event.github.ref
  Xray:
    env:
      PYTHONUNBUFFERED: "1"
    resources:
      instance-type: C7
    needs:
      - CloneRepo
    inputs:
      xray: CloneRepo.outputs.xray
    outputs:
      xrayoutputs:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        cd /inputs/xray
        pip install matplotlib
        python main.py 
      image: nvcr.io/nvidia/pytorch:21.07-py3
# nvcr.io/nvidia/pytorch:21.07-py3
# pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime
# pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime
# pytorch/pytorch:latest
